### ISSUE TITLE
It's not working if the html tag have 100% height.

### ISSUE THREAD

**Issue by graydirt** [mleralec/react-progressbar-on-scroll#12]
It's not working if the html tag have 100% height. That 100% height is a part of my template and I don't want to remove it. Any thoughts or suggestions? See [codepen](https://codesandbox.io/s/react-progressbar-on-scroll-7q3q3c)

**Comment by mleralec** [comment]
Hey @graydirt,
I think it is the normal behavior because the progressbar only works if there if something to scroll in your page.
What do you think ?

**Comment by graydirt** [comment]
> 

Hi @mleralec yeah i think so, but I'm going to try the styled-components inside react-progressbar-on-scroll props. Here is the reference [codesandbox](https://codesandbox.io/s/i0k8e8). And can we keep this issues open?, maybe someone might help up. thx
