### ISSUE TITLE
Module not found: Can't resolve 'react-scroll-on-progressbar'

### ISSUE THREAD

**Issue by jobayer-h** [mleralec/react-progressbar-on-scroll#6]
please fix your documentation.

`import ProgressBar from 'react-progressbar-on-scroll'`

**Comment by mleralec** [comment]
What is your problem? Check this sandbox, the default import is working ! https://codesandbox.io/s/condescending-easley-qgiyn

If you get this error :`Can't resolve 'react-scroll-on-progressbar'` try to run a `npm i react-scroll-on-progressbar`

**Comment by jobayer-h** [comment]
`'import ProgressBar from 'react-progressbar-on-scroll`' it works fine. 

but in your github redme.md,  `import ProgressBar from 'react-scroll-on-progressbar'..`.  its not working. so **update your readme.md file.**

**Comment by mleralec** [comment]
You're right ! I have just publish a fix, thanks @jobayer-h 😄
